sudo: required
dist: trusty

stages:
  - test
  - deploy

language: node_js
node_js: 8

cache:
  directories:
    - $HOME/haxe

os:
  - linux
  # - osx

env:
  - HAXE_VERSION=3.4.7
  - HAXE_VERSION=latest
  
install:
  - git clone https://github.com/localstack/localstack
  - docker pull localstack/localstack
  - pushd localstack && docker-compose up -d && popd
  - npm i -g lix
  - pushd bin/node && yarn && popd
  - lix install haxe $HAXE_VERSION
  - lix download
  
script:
  - lix run travix node
