sudo: required
dist: trusty

stages:
  - test
  - deploy

language: node_js
node_js: 8

cache:
  directories:
    - $HOME/haxe

os:
  - linux
  # - osx

env:
  - HAXE_VERSION=3.4.7
  - HAXE_VERSION=latest
  
install:
  - docker-compose -f submodules/localstack/docker-compose.yml up -d
  - npm i -g lix
  - pushd bin/node && yarn && popd
  - lix install haxe $HAXE_VERSION
  - lix download
  - export AWS_ACCESS_KEY_ID=dummy
  - export AWS_SECRET_ACCESS_KEY=dummy
  
script:
  - lix run travix node
